# fly.toml app configuration file generated for link-sharing-app on 2023-07-10T17:43:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "link-sharing-app"
primary_region = "lhr"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  DB_HOST = "link-sharing-db.internal"
  DB_DATABASE= "some_db"
  SSR_URL="ssr.process.link-sharing-app.internal:13714"
  APP_URL = "https://link-sharing-app.fly.dev"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[processes]
  app=""
  ssr="php /var/www/html/artisan inertia:start-ssr"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[mounts]
  source="storage_vol"
  destination="/var/www/html/storage"
